// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actionupdate/v1/update.proto

package com.github.thepwagner.actionupdate.v1.rpc;

public final class Update {
  private Update() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DependencyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:actionupdate.v1.Dependency)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>bool indirect = 3;</code>
     * @return The indirect.
     */
    boolean getIndirect();
  }
  /**
   * Protobuf type {@code actionupdate.v1.Dependency}
   */
  public static final class Dependency extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:actionupdate.v1.Dependency)
      DependencyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dependency.newBuilder() to construct.
    private Dependency(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dependency() {
      path_ = "";
      version_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dependency();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dependency(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 24: {

              indirect_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_Dependency_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_Dependency_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.class, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder.class);
    }

    public static final int PATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object path_;
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDIRECT_FIELD_NUMBER = 3;
    private boolean indirect_;
    /**
     * <code>bool indirect = 3;</code>
     * @return The indirect.
     */
    @java.lang.Override
    public boolean getIndirect() {
      return indirect_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      if (indirect_ != false) {
        output.writeBool(3, indirect_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      if (indirect_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, indirect_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency)) {
        return super.equals(obj);
      }
      com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency other = (com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency) obj;

      if (!getPath()
          .equals(other.getPath())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (getIndirect()
          != other.getIndirect()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + INDIRECT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIndirect());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code actionupdate.v1.Dependency}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:actionupdate.v1.Dependency)
        com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_Dependency_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_Dependency_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.class, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder.class);
      }

      // Construct using com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        path_ = "";

        version_ = "";

        indirect_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_Dependency_descriptor;
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency getDefaultInstanceForType() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency build() {
        com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency buildPartial() {
        com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency result = new com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency(this);
        result.path_ = path_;
        result.version_ = version_;
        result.indirect_ = indirect_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency) {
          return mergeFrom((com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency other) {
        if (other == com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.getDefaultInstance()) return this;
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getIndirect() != false) {
          setIndirect(other.getIndirect());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>string path = 1;</code>
       * @return The path.
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 2;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private boolean indirect_ ;
      /**
       * <code>bool indirect = 3;</code>
       * @return The indirect.
       */
      @java.lang.Override
      public boolean getIndirect() {
        return indirect_;
      }
      /**
       * <code>bool indirect = 3;</code>
       * @param value The indirect to set.
       * @return This builder for chaining.
       */
      public Builder setIndirect(boolean value) {
        
        indirect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool indirect = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndirect() {
        
        indirect_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:actionupdate.v1.Dependency)
    }

    // @@protoc_insertion_point(class_scope:actionupdate.v1.Dependency)
    private static final com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency();
    }

    public static com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dependency>
        PARSER = new com.google.protobuf.AbstractParser<Dependency>() {
      @java.lang.Override
      public Dependency parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dependency(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dependency> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dependency> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListDependenciesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:actionupdate.v1.ListDependenciesRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code actionupdate.v1.ListDependenciesRequest}
   */
  public static final class ListDependenciesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:actionupdate.v1.ListDependenciesRequest)
      ListDependenciesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListDependenciesRequest.newBuilder() to construct.
    private ListDependenciesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListDependenciesRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ListDependenciesRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListDependenciesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest.class, com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest)) {
        return super.equals(obj);
      }
      com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest other = (com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code actionupdate.v1.ListDependenciesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:actionupdate.v1.ListDependenciesRequest)
        com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest.class, com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest.Builder.class);
      }

      // Construct using com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesRequest_descriptor;
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest getDefaultInstanceForType() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest build() {
        com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest buildPartial() {
        com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest result = new com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest) {
          return mergeFrom((com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest other) {
        if (other == com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:actionupdate.v1.ListDependenciesRequest)
    }

    // @@protoc_insertion_point(class_scope:actionupdate.v1.ListDependenciesRequest)
    private static final com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest();
    }

    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListDependenciesRequest>
        PARSER = new com.google.protobuf.AbstractParser<ListDependenciesRequest>() {
      @java.lang.Override
      public ListDependenciesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListDependenciesRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListDependenciesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListDependenciesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListDependenciesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:actionupdate.v1.ListDependenciesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    java.util.List<com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency> 
        getDependenciesList();
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency getDependencies(int index);
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    int getDependenciesCount();
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    java.util.List<? extends com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder> 
        getDependenciesOrBuilderList();
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder getDependenciesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code actionupdate.v1.ListDependenciesResponse}
   */
  public static final class ListDependenciesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:actionupdate.v1.ListDependenciesResponse)
      ListDependenciesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListDependenciesResponse.newBuilder() to construct.
    private ListDependenciesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListDependenciesResponse() {
      dependencies_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ListDependenciesResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListDependenciesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                dependencies_ = new java.util.ArrayList<com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency>();
                mutable_bitField0_ |= 0x00000001;
              }
              dependencies_.add(
                  input.readMessage(com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse.class, com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse.Builder.class);
    }

    public static final int DEPENDENCIES_FIELD_NUMBER = 1;
    private java.util.List<com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency> dependencies_;
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency> getDependenciesList() {
      return dependencies_;
    }
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder> 
        getDependenciesOrBuilderList() {
      return dependencies_;
    }
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    @java.lang.Override
    public int getDependenciesCount() {
      return dependencies_.size();
    }
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    @java.lang.Override
    public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency getDependencies(int index) {
      return dependencies_.get(index);
    }
    /**
     * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
     */
    @java.lang.Override
    public com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder getDependenciesOrBuilder(
        int index) {
      return dependencies_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dependencies_.size(); i++) {
        output.writeMessage(1, dependencies_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dependencies_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dependencies_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse)) {
        return super.equals(obj);
      }
      com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse other = (com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse) obj;

      if (!getDependenciesList()
          .equals(other.getDependenciesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDependenciesCount() > 0) {
        hash = (37 * hash) + DEPENDENCIES_FIELD_NUMBER;
        hash = (53 * hash) + getDependenciesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code actionupdate.v1.ListDependenciesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:actionupdate.v1.ListDependenciesResponse)
        com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse.class, com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse.Builder.class);
      }

      // Construct using com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDependenciesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dependenciesBuilder_ == null) {
          dependencies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dependenciesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.internal_static_actionupdate_v1_ListDependenciesResponse_descriptor;
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse getDefaultInstanceForType() {
        return com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse build() {
        com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse buildPartial() {
        com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse result = new com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse(this);
        int from_bitField0_ = bitField0_;
        if (dependenciesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dependencies_ = dependencies_;
        } else {
          result.dependencies_ = dependenciesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse) {
          return mergeFrom((com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse other) {
        if (other == com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse.getDefaultInstance()) return this;
        if (dependenciesBuilder_ == null) {
          if (!other.dependencies_.isEmpty()) {
            if (dependencies_.isEmpty()) {
              dependencies_ = other.dependencies_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDependenciesIsMutable();
              dependencies_.addAll(other.dependencies_);
            }
            onChanged();
          }
        } else {
          if (!other.dependencies_.isEmpty()) {
            if (dependenciesBuilder_.isEmpty()) {
              dependenciesBuilder_.dispose();
              dependenciesBuilder_ = null;
              dependencies_ = other.dependencies_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dependenciesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDependenciesFieldBuilder() : null;
            } else {
              dependenciesBuilder_.addAllMessages(other.dependencies_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency> dependencies_ =
        java.util.Collections.emptyList();
      private void ensureDependenciesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          dependencies_ = new java.util.ArrayList<com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency>(dependencies_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder, com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder> dependenciesBuilder_;

      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public java.util.List<com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency> getDependenciesList() {
        if (dependenciesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dependencies_);
        } else {
          return dependenciesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public int getDependenciesCount() {
        if (dependenciesBuilder_ == null) {
          return dependencies_.size();
        } else {
          return dependenciesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency getDependencies(int index) {
        if (dependenciesBuilder_ == null) {
          return dependencies_.get(index);
        } else {
          return dependenciesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder setDependencies(
          int index, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.set(index, value);
          onChanged();
        } else {
          dependenciesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder setDependencies(
          int index, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.set(index, builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder addDependencies(com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.add(value);
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder addDependencies(
          int index, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.add(index, value);
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder addDependencies(
          com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.add(builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder addDependencies(
          int index, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.add(index, builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder addAllDependencies(
          java.lang.Iterable<? extends com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency> values) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dependencies_);
          onChanged();
        } else {
          dependenciesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder clearDependencies() {
        if (dependenciesBuilder_ == null) {
          dependencies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dependenciesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public Builder removeDependencies(int index) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.remove(index);
          onChanged();
        } else {
          dependenciesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder getDependenciesBuilder(
          int index) {
        return getDependenciesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder getDependenciesOrBuilder(
          int index) {
        if (dependenciesBuilder_ == null) {
          return dependencies_.get(index);  } else {
          return dependenciesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public java.util.List<? extends com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder> 
           getDependenciesOrBuilderList() {
        if (dependenciesBuilder_ != null) {
          return dependenciesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dependencies_);
        }
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder addDependenciesBuilder() {
        return getDependenciesFieldBuilder().addBuilder(
            com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.getDefaultInstance());
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder addDependenciesBuilder(
          int index) {
        return getDependenciesFieldBuilder().addBuilder(
            index, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.getDefaultInstance());
      }
      /**
       * <code>repeated .actionupdate.v1.Dependency dependencies = 1;</code>
       */
      public java.util.List<com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder> 
           getDependenciesBuilderList() {
        return getDependenciesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder, com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder> 
          getDependenciesFieldBuilder() {
        if (dependenciesBuilder_ == null) {
          dependenciesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency, com.github.thepwagner.actionupdate.v1.rpc.Update.Dependency.Builder, com.github.thepwagner.actionupdate.v1.rpc.Update.DependencyOrBuilder>(
                  dependencies_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          dependencies_ = null;
        }
        return dependenciesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:actionupdate.v1.ListDependenciesResponse)
    }

    // @@protoc_insertion_point(class_scope:actionupdate.v1.ListDependenciesResponse)
    private static final com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse();
    }

    public static com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListDependenciesResponse>
        PARSER = new com.google.protobuf.AbstractParser<ListDependenciesResponse>() {
      @java.lang.Override
      public ListDependenciesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListDependenciesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListDependenciesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListDependenciesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.thepwagner.actionupdate.v1.rpc.Update.ListDependenciesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_actionupdate_v1_Dependency_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_actionupdate_v1_Dependency_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_actionupdate_v1_ListDependenciesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_actionupdate_v1_ListDependenciesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_actionupdate_v1_ListDependenciesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_actionupdate_v1_ListDependenciesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034actionupdate/v1/update.proto\022\017actionup" +
      "date.v1\"=\n\nDependency\022\014\n\004path\030\001 \001(\t\022\017\n\007v" +
      "ersion\030\002 \001(\t\022\020\n\010indirect\030\003 \001(\010\"\031\n\027ListDe" +
      "pendenciesRequest\"M\n\030ListDependenciesRes" +
      "ponse\0221\n\014dependencies\030\001 \003(\0132\033.actionupda" +
      "te.v1.Dependency2x\n\rUpdateService\022g\n\020Lis" +
      "tDependencies\022(.actionupdate.v1.ListDepe" +
      "ndenciesRequest\032).actionupdate.v1.ListDe" +
      "pendenciesResponseBl\n)com.github.thepwag" +
      "ner.actionupdate.v1.rpcZ?github.com/thep" +
      "wagner/action-update-twirp/proto/actionu" +
      "pdate/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_actionupdate_v1_Dependency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_actionupdate_v1_Dependency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_actionupdate_v1_Dependency_descriptor,
        new java.lang.String[] { "Path", "Version", "Indirect", });
    internal_static_actionupdate_v1_ListDependenciesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_actionupdate_v1_ListDependenciesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_actionupdate_v1_ListDependenciesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_actionupdate_v1_ListDependenciesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_actionupdate_v1_ListDependenciesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_actionupdate_v1_ListDependenciesResponse_descriptor,
        new java.lang.String[] { "Dependencies", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
